/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ContactCard: typeof import('./src/components/ContactCard.vue')['default']
    ContactModal: typeof import('./src/components/ContactModal.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconMaterialSymbolsAlternateEmail: typeof import('~icons/material-symbols/alternate-email')['default']
    IconMaterialSymbolsPhoneEnabled: typeof import('~icons/material-symbols/phone-enabled')['default']
    IconOcticonChevronDown16: typeof import('~icons/octicon/chevron-down16')['default']
    IconOcticonPencil16: typeof import('~icons/octicon/pencil16')['default']
    IconOcticonPerson16: typeof import('~icons/octicon/person16')['default']
    IconOcticonPlus16: typeof import('~icons/octicon/plus16')['default']
    IconOcticonTrash16: typeof import('~icons/octicon/trash16')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NoData: typeof import('./src/components/NoData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
